# Generated by Django 6.0.4 on 2026-04-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(help_text='e.g., IT, AI, Engineering', max_length=100)),
                ('employment_type', models.CharField(default='Full-time', max_length=100)),
                ('work_mode', models.CharField(help_text='e.g., Remote, On-site, Hybrid', max_length=100)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(help_text='The full job description for ATS analysis')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
